### ISSUE TITLE
File libpowersync_x64.dylib does not exist

### ISSUE THREAD

**Issue by tva77** [powersync-ja/powersync-sqlite-core#31]
on Flutter project, when I run melos prepare:

`Downloading: https://github.com/powersync-ja/powersync-sqlite-core/releases/download/v0.2.1/libpowersync_x64.dylib
Failed to download file: 404 Not Found
File libpowersync_x64.dylib does not exist.
`

**Comment by mugikhan** [comment]
Hey @tva77 thanks for reporting this. We have published the `libpowersync_x64.dylib` binary to the latest release. Please confirm that it the `melos prepare` command works for you.

**Comment by tva77** [comment]
works fine!!
thank you!!
